version: "3"
services:
  server:
    build: back-end
    ports:
      - "5500:5500"
    volumes:
      - ./log:/log
  client:
    build: 
      context: ./
      dockerfile: ./front.docker
    ports:
      - "3000:3000"
    depends_on:
      - server